"""
investigation.py
----------------
Shared contracts for the Agentic SOC Investigation Platform.
These schemas act as the strict boundaries between components.
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class PlannerError(Exception):
    """Raised when the LLM Planner completely fails after all retries."""
    pass


# ═══════════════════════════════════════════════════════════════════════════════
# CONTRACT 3: ToolResult
# Returned by every specialist tool.
# ═══════════════════════════════════════════════════════════════════════════════

class ToolResult(BaseModel):
    tool_name: str = Field(..., description="Name of the specialist tool")
    reason_selected: str = Field(default="Default execution", description="Why the planner selected this tool")
    expected_evidence: str = Field(default="Standard evidence", description="What the planner expects this tool to find")
    evidence: Any = Field(..., description="Structured evidence generated by the tool")
    confidence: float = Field(0.0, description="Confidence score from 0.0 to 1.0")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Execution metadata, tags, context")
    execution_time: float = Field(..., description="Time taken to execute in ms")
    provenance: str = Field(..., description="Identifier of the system/model generating the result")


# ═══════════════════════════════════════════════════════════════════════════════
# CONTRACT 2: InvestigationPlan
# Generated ONLY by the Planner, consumed by Policy Engine and Orchestrator.
# ═══════════════════════════════════════════════════════════════════════════════

class ToolIntent(BaseModel):
    tool_name: str = Field(..., description="Name of the specialist tool")
    reason_selected: str = Field(..., description="Reason for selecting this tool")
    expected_evidence: str = Field(..., description="Expected evidence to find")

class InvestigationPlan(BaseModel):
    hypothesis: str = Field(..., description="Working hypothesis of the investigation")
    uncertainty: float = Field(..., description="Uncertainty level from 0.0 to 1.0")
    required_tools: List[ToolIntent] = Field(..., description="List of specialist tools requested with reasoning")
    execution_strategy: str = Field(..., description="Sequential or Parallel execution intent")
    stop_conditions: List[str] = Field(..., description="Conditions under which execution stops")
    reasoning: str = Field(..., description="Planner's reasoning for this plan")


# ═══════════════════════════════════════════════════════════════════════════════
# CONTRACT 1: InvestigationObject
# The single source of truth for the entire pipeline.
# ═══════════════════════════════════════════════════════════════════════════════

class InvestigationObject(BaseModel):
    # ── Perception Layer Populated ──
    investigation_id: str = Field(..., description="Unique ID for this investigation")
    session_metadata: Dict[str, Any] = Field(default_factory=dict, description="Session and timeline summaries")
    normalized_events: List[Dict[str, Any]] = Field(default_factory=list, description="Sanitized events list")
    entity_info: Dict[str, Any] = Field(default_factory=dict, description="Information about the primary entity")
    
    # Quarantined Data (not serialized by default for planner)
    raw_logs_quarantine: str = Field("", description="Raw logs for tool consumption only")
    
    # ── Planner Populated ──
    planner_hypothesis: str = Field("", description="Current working hypothesis")
    
    # ── Tool / Aggregator Populated ──
    tool_outputs: List[ToolResult] = Field(default_factory=list, description="All tool results")
    evidence_timeline: List[Dict[str, Any]] = Field(default_factory=list, description="Merged timeline of evidence")
    evidence_completeness: float = Field(0.0, description="Percentage of available specialist tools utilized")
    
    # ── Decision Engine Populated ──
    confidence: float = Field(0.0, description="Overall deterministic confidence")
    severity: str = Field("UNKNOWN", description="Deterministic severity level")
    risk: float = Field(0.0, description="Deterministic risk score")
    decision: str = Field("PENDING", description="Recommended action")
    
    # ── Report Generator Populated ──
    report: str = Field("", description="Final LLM generated markdown report")
    
    # ── Runtime Tracking (populated by agent_layer.py) ──
    confidence_evolution: List[float] = Field(default_factory=list, description="Confidence after each iteration")
    reflection_history: List[Dict[str, Any]] = Field(default_factory=list, description="Reflection decisions per iteration")
    replan_events: List[Dict[str, Any]] = Field(default_factory=list, description="Replan events with reasons")
    plan_iterations: int = Field(1, description="Total planner iterations executed")
    severity_factors: List[str] = Field(default_factory=list, description="Human-readable factors that influenced severity")
    investigation_report: Dict[str, Any] = Field(default_factory=dict, description="Structured report with sections")
    skipped_tools_log: List[Dict[str, str]] = Field(default_factory=list, description="Log of skipped tools and reasons")
    last_reflection_data: Dict[str, Any] = Field(default_factory=dict, description="Structured data from the last reflection")
    confidence_breakdown: Dict[str, float] = Field(default_factory=dict, description="Breakdown of confidence factors")
    risk_breakdown: Dict[str, float] = Field(default_factory=dict, description="Breakdown of risk factors")
    
    def to_planner_dict(self) -> Dict[str, Any]:
        """Provides a safe, sanitized subset of the object for the LLM Planner."""
        
        # Aggressively prune the timeline to preserve context window for local models
        pruned_timeline = self.evidence_timeline
        if len(pruned_timeline) > 5:
            pruned_timeline = pruned_timeline[-5:]
            
        return {
            "investigation_id": self.investigation_id,
            "session_metadata": self.session_metadata,
            "normalized_events": self.normalized_events,
            "entity_info": self.entity_info,
            "evidence_timeline": pruned_timeline,
            "tool_names_run": [t.tool_name for t in self.tool_outputs],
            "confidence": self.confidence,
        }
